name: Nightly Full Test Suite

on:
  schedule:
    # Ejecutar todas las noches a las 2:00 AM UTC (11:00 PM Argentina)
    # Permitir ejecución manual
  workflow_dispatch:

jobs:
  nightly-test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Validate secrets
      run: |
        if [ -z "${{ secrets.LOGIN_USERNAME }}" ]; then
          echo "❌ LOGIN_USERNAME secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.LOGIN_PASSWORD }}" ]; then
          echo "❌ LOGIN_PASSWORD secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.BASE_URL }}" ]; then
          echo "❌ BASE_URL secret is not set"
          exit 1
        fi
        echo "✅ All secrets are configured"
    
    - name: Run Full Playwright Test Suite (Nightly)
      run: npx playwright test
      env:
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
        PLAYWRIGHT_BROWSERS: 0
    
    - name: Generate Allure Report
      if: always()
      run: |
        npx allure generate allure-results --clean -o allure-report
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nightly-allure-report
        path: allure-report/
        retention-days: 7
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nightly-playwright-report
        path: playwright-report/
        retention-days: 7
